import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { Router, useRouter } from "next/router";
import { useEffect } from "react";
import { loginUser } from "../lib/helpers";
import Login from "./login";

export default function Home() {
  const { data: session, status } = useSession();
  const router = useRouter();
  if (status == "authenticated") {
    return (
      <div className="max-w-7xl mx-auto">
        <Head>
          <title>Login </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <button onClick={signOut}>SignOut</button>
        </main>
      </div>
    );
  } else {
    return <Login />;
  }
}
